apiVersion: apps/v1
kind: Deployment
metadata:
  name: cont1-deployment
  labels:
    app: cont1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cont1
  template:
    metadata:
      labels:
        app: cont1
    spec:
      containers:
      - name: cont1
        image: bquintero56/pagina:latest
        ports:
        - containerPort: 80
