name: build
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: confi kubectl 
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
          echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
          
      - name: install kubectl 
        run: |
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client
      - uses: actions/checkout@v2
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          
      - name: conet cluster
        run: aws eks update-kubeconfig --region us-east-2 --name ${{ secrets.REPO }}
        
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.USER_DOCKER }}
        # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.PASS_DOCKER }}
    
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker build -t bquintero56/pagina .
          docker tag bquintero56/pagina bquintero56/pagina
          docker push bquintero56/pagina
          
      - name: docker images
        run: docker images 
                
      - name: 'deployment'
        run: |
          kubectl delete -f deployment.yaml -n mongo
          kubectl apply -f deployment.yaml -n mongo
          
        
