name: Docker Image CI

on:
  push:
    branches: [ "develop" ]

permissions:
      id-token: write
      contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: 'Az CLI login'
      run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    - name: 'Run az commands'
      run: |
          az login

