name: Docker Image CI

on:
  push:
    branches: [ "develop" ]

permissions:
      id-token: write
      contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.USER_DOCKER }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.PASS_DOCKER }}
        
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build -t bquintero56/pagina .
        docker tag bquintero56/pagina bquintero56/pagina
        docker push bquintero56/pagina
    - name: docker images
      run: docker images 
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: 'Run az commands'
      run: |
          az account show

